### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pa-0** [originates/HashCheck#2]
This looks awesome.  I think it's exactly the solution I've been looking for too.  

Question: will this allow me to leverage all the existing macros I have saved in the excel template file that I choose to distribute with the script?

For instance, I am thinking of creating a simple search box where the user can type the function they want, choose from the result, and it would either a) run the macro on the active workbook (if no additional inputs are required) or b) prompt the user to enter whatever parameters need to be fed to the macro.

Is this feasible with this script?

**Comment by GithubUserAccountAmazing** [comment]
It's been a while since I've used this script but if I remember correctly you will be able to use all existing macros, however, since it opens the excel file as a template of the original xlsm file you may need to update your scripts to work with the template instead. Hope this helps.

**Comment by pa-0** [comment]
This definitely helps.  Thanks!
